### ISSUE TITLE
Not all subscribers observe the same event order given multiple publishers

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-eventbus#16]
This means "last value" is a fuzzy concept.

**Comment by magik6k** [comment]
I'm not really sure what would be the right way to guarantee event order in case where you have publishers in separate goroutines without impacting the performance a lot.

Possibly for some components we could implement a wrapper around the eventbus interface which would allow only one goroutine to emit at a time.

**Comment by Stebalien** [comment]
Is not allowing concurrent publishes on a single topic really _that_ big of a perf issue? Like, a real perf issue that matters?

**Comment by magik6k** [comment]
No, that's fine, I thought you meant across multiple topics.

This should be as simple as changing this RWMutex - https://github.com/libp2p/go-eventbus/blob/master/basic.go#L231 to a normal one

**Comment by Stebalien** [comment]
Yep, that's what I meant.
