### ISSUE TITLE
go-eventbus panics when removing StreamHandler after cancelling host context

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-eventbus#20]
I think this is a regression.  Removing StreamHandlers after the host context's been cancelled causes go-eventbus to panic because emmitters have been closed:

```
panic: emitter is closed

goroutine 71 [running]:
github.com/libp2p/go-eventbus.(*emitter).Emit(0xc000191200, 0xc81540, 0xc0000b7980)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-eventbus@v0.0.3/basic.go:33 +0x6f
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).RemoveStreamHandler(0xc0000d62c0, 0xd4501d, 0xc)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-libp2p@v0.2.1/p2p/host/basic/basic_host.go:419 +0x112
github.com/libp2p/go-libp2p-gostream.(*listener).Close(0xc000046400, 0xc00014add0, 0x10)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-libp2p-gostream@v0.1.2/listener.go:39 +0x53
net/http.(*onceCloseListener).close(...)
	/usr/local/go/src/net/http/server.go:3286
sync.(*Once).Do(0xc0000b7570, 0xc00014ae00)
	/usr/local/go/src/sync/once.go:44 +0xb3
net/http.(*onceCloseListener).Close(0xc0000b7560, 0x0, 0x55)
	/usr/local/go/src/net/http/server.go:3282 +0x54
net/http.(*Server).Serve(0xc0003684e0, 0xf91f80, 0xc000046400, 0xf815e0, 0xc0000b2210)
	/usr/local/go/src/net/http/server.go:2879 +0x4b0
github.com/ipfs/ipfs-cluster/api/rest.(*API).runLibp2pServer(0xc00012b050, 0xf95700, 0xc000362980)
	/home/kishan/code/ipfs-cluster/api/rest/restapi.go:477 +0x322
created by github.com/ipfs/ipfs-cluster/api/rest.(*API).run
	/home/kishan/code/ipfs-cluster/api/rest/restapi.go:449 +0x8a
FAIL	github.com/ipfs/ipfs-cluster/api/rest	0.094s
```

**Comment by bigs** [comment]
@raulk yep, taking a look

**Comment by bigs** [comment]
@hsanjuan Seems like the only way to really fix this without incurring a breaking change would be to add a helper function to `BasicHost` that only emits when the `goprocess` isn't closed. That, or downgrade the `panic` to an error/warning log. Any thoughts?

Edit: Either way, it should be a pretty simple fix.

**Comment by hsanjuan** [comment]
This is the second regression-panic related to using the Emit() when the emitter is closed in a few days, I don't know how many other ways there are to trigger such panics, but given how the eventbus has been introduced, I'm leaning to think that if the emitter is closed, `Emit()` should be a no-op (with a warning perhaps)...

**Comment by Kubuxu** [comment]
It should probably return an error.

**Comment by bigs** [comment]
@Kubuxu That's my gut as well. Since it's early days, perhaps it's okay to incur the breakage? I suppose it won't actually break existing code, either.

**Comment by bigs** [comment]
Resolved in https://github.com/libp2p/go-eventbus/releases/tag/v0.1.0 and will be released with next go-libp2p.
