### ISSUE TITLE
option to accumulate events during startup

### ISSUE THREAD

**Issue by raulk** [libp2p/go-eventbus#5]
When constructing the BasicHost, we create an event bus. During initialisation, we register protocol handlers for identify. Other events may happen as well in the future. Unfortunately, these events are lost due to a catch-22. The consumer has no access to the `EventBus` until `libp2p.New()` has returned, yet the events are generated before we return.

We should introduce an option that accumulates events and releases them on the same order they were accumulated when the user calls `eventbus.ReleaseQueuedEvents()`.

**Comment by magik6k** [comment]
Another way could be keeping a sequence number in identify and in events, and when joining the bus:

* join the bus
* get state from identify, including the sequence number
* start applying deltas when event sequence number is larger than the one in identify

**Comment by aarshkshah1992** [comment]
@raulk  Please can I go ahead & pick this up ? I'll share some notes/code later based on the comments above.

**Comment by aarshkshah1992** [comment]
@raulk 

I think you are referring to the loss of `EvtPeerProtocolsUpdated` events (and possibly more in the future)  emitted by the `ID service` if a connected peer changes it's protocol stack before `libp2p.New` returns.

If we were to build an accumulator in the event bus to accumulate say X events for a 'topic'(type), 
should we clear the accumulator after passing the events to the first guy who calls `ReleaseQueuedEvents`(dosen't make sense) or should we keep it in memory for all future callers until someone calls `ClearQueuedEvents` (**possibly with a timeout to prevent leaks**)?

So, the  changes I have in mind are :

```
type emitterSettings struct {  
   ...
   accumulatorSize int 
   accumulatorTTL time.Duration 
}

type Bus interface {
  ReleaseQueuedEvents(eventType interface{}) []interface{}
 
  ClearQueuedEvents(eventType interface{}) error
}
```
@magik6k Please can you elaborate a bit more on your approach ? I am not being able to fathom how it will prevent loss of events. Also, I think a solution in the `eventbus` is better than writing one just for `Identify` as we _could_ face the same problem for other `emitters` in the future.

**Comment by marten-seemann** [comment]
I believe this has been resolved by the introduction of `Stateful`.
